apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "echo.fullname" . }}
  labels:
    {{- include "echo.labels" . | nindent 4 }}
data:
  PORT: '3000'
  LOGLEVEL: 'debug'
  PERSIST: 'True'
  MONGODBURL:  'mongodb://mongodb-0.mongodb,mongodb-1.mongodb,mongodb-2.mongodb:27017/echo?authSource=admin'
  DBNAME: 'echo'

